.MODEL SMALL
.STACK 100H
.DATA ;Data Segment
MSG DB 'HELLO $'
.CODE ;Code Segment
MAIN PROC ;Main func
MOV AX,@DATA
MOV DS,AX
LEA DX, MSG ;LOAD EFFECTIVE ADDRESS
MOV AH,9
INT 21H
MOV AH, 4CH ;DOS EXIT
INT 21H
MAIN ENDP
END MAIN